IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[SP_GET_NAVBAR_LIST]'))
BEGIN
DROP PROCEDURE  SP_GET_NAVBAR_LIST
END
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

--			SP_GET_NAVBAR_LIST '1'


CREATE PROCEDURE [dbo].[SP_GET_NAVBAR_LIST]  
(
@RoleId INT
)
AS
BEGIN	

	SELECT * FROM Navbar WHERE IsDeleted = 0 AND RoleId = @RoleId ORDER BY DisplayOrder ASC;

END